version: "3.4"

networks:
  backend:
  frontend:

volumes:
  netflixprojectV1.postgres-database:

services:
  postgres:
    container_name: postgres
    image: postgres:11.12
    volumes:
      - netflixprojectV1.postgres-database:/var/lib/postgresql/data
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netflixProject"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  netflix-backend:
    container_name: backend
    build:
      context: ./netflixProjectBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run dev"
    networks:
      - backend
      - frontend
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  
  netflix-frontend:
    container_name: frontend
    build:
      context: ./netflix-project-react
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - BACKEND_API_URL = http://localhost:3000
    networks:
      - frontend
    depends_on:
      - netflix-backend